const examples = [
    ['o','<b>o</b>dd'],
    ['ah','m<b>a</b>tter'],
    ['uh','h<b>u</b>t'],
    ['ow','h<b>o</b>w'],
    ['I','m<b>i</b>nd'],
    ['b','<b>b</b>etter'],
    ['ch','<b>ch</b>oose'],
    ['d','<b>d</b>iorite'],
    ['th','<b>th</b>ere'],
    ['e','b<b>e</b>tter'],
    ['er','flutt<b>er</b>'],
    ['ay','m<b>a</b>ke'],
    ['f','<b>f</b>ix'],
    ['gh','<b>g</b>reen'],
    ['h','<b>h</b>igh'],
    ['ih','m<b>i</b>x'],
    ['ee','n<b>ee</b>d'],
    ['j','<b>j</b>ump'],
    ['k, hard c','<b>k</b>ite'],
    ['Lh', '<b>l</b>ong'],
    ['m','<b>m</b>ight'],
    ['n','<b>n</b>ice'],
    ['ng','pi<b>ng</b>'],
    ['oh', 'sn<b>o</b>w'],
    ['oi','m<b>oi</b>st'],
    ['p', '<b>p</b>late'],
    ['r', '<b>r</b>oad'],
    ['s', '<b>s</b>ort'],
    ['sh', '<b>sh</b>ort'],
    ['hard t', '<b>t</b>ake'],
    ['oh', 'b<b>oo</b>k'],
    ['ooh', 'y<b>ou</b>'],
    ['v', '<b>v</b>ery'],
    ['w', '<b>w</b>ild'],
    ['y', '<b>y</b>es'],
    ['z', '<b>z</b>ip'],
];